audit_header: false
title: Global Real Estate Video Blog with Bud & Kristin Gragg
description: >-
  Our mission at eXp Realty is to be your best resource for real estate advice.
  Whether you are a buyer, seller, or investor, our team of professionals can
  answer any questions you might have about real estate. If you are looking to
  buy or sell a home, you can get all the information and the latest updates,
  tips, and tricks from The eXp Realty, your professional Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:
client:
  name: Bud & Kristin Gragg
  title:
  license_number:
  about_markdown: >-
    <span class="about-subtitle">Mission</span><br>• To Serve as Consummate Real
    Estate Professionals and Leave a Legacy of Authenticity, Real Relationships
    and Positively Outrageous Customer Service — While Having Fun! We are NOT
    Sales People, We are Business Owners<br><br><span
    class="about-subtitle">Vision</span><br>• A Reputation for the Most Trusted
    Real Estate Team<br><br><span class="about-subtitle">Values</span><br>• God,
    Family, Bucket List, Business, While Having Fun!<br><br><span
    class="about-subtitle">Beliefs</span><br>• Win-Win or No Deal<br>• Integrity
    - Do the Right Thing Always<br>• Customers are always First<br>• Commitment
    - &nbsp;In all things<br>• Communication - Seek First to Understand<br>•
    Creativity - Ideas Before Results<br>• Teamwork - Together We Achieve
    More<br>• Trust - Starts with Honesty<br>• Success - Real Results through
    People<br><br><span class="about-subtitle">Perspective/Slogan</span><br>Real
    **Relationships,** Real **Expectations,** Real **Service,** Real **Results**
    — We Put the **Real** in Real Estate
  brand: eXp Realty
  brokerage:
  market: Phoenix
  address: '3238 East Goldfinch Way<br>Chandler, AZ 85286'
  phone: (480) 497-5600
  phone_type: Bud
  phone2: (602) 882-3700
  phone2_type: Kristin
  email: BudGragg@gmail.com
  email_type: Bud
  email2: KristinGragg1@gmail.com
  email2_type: Kristin
  url: 'http://www.budknowsrealestate.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.whatsmypadworth.com/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://myre.io/0LQtVIK9poHDB/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: What’s Your Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'http://www.whatsmypadworth.com/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: Looking for a Home?
    CTA_text2: Search the entire MLS for your home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'https://myre.io/0LQtVIK9poHDB'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/BKGInternational'
  linkedin_url: 'https://www.linkedin.com/in/kristingragg/'
  youtube_url: 'https://www.youtube.com/channel/UCkFIYSoXZ93UOOKsG6aTIhQ'
  twitter_url: 'https://twitter.com/BudGragg'
  instagram_url: 'https://www.instagram.com/bkginternationalrealestate/'
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Global Real Estate Podcast with Bud & Kristin Gragg
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Phoenix
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from eXp Realty - your professional Phoenix
    Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Phoenix, home
    selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Bud & Kristin Gragg
images:
  client_headshot_path: /uploads/-p5i3928.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text:
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#19469d'
  theme_color: '#00021a'
  accent_color: '#f5821f'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'